name: julianhartline.com
owner: Julian Hartline
email: julianh2o@gmail.com
titletagline: Code, circuits, and commentary
tagline: Programmings, tinkerings, and musings to stave off idleness.
github: julianh2o
exclude: [tasks, misc_unused]
markdown: redcarpet
highlighter: pygments
permalink: none
